// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 WFT345 and AlpenSync contributors
// Adapted from pcontacts (GPL-3.0), https://github.com/andreabenetton/pcontacts @ bf9b0c5,
// path core/crypto/src/test/kotlin/io/pcontacts/core/crypto/CapturedVectorsTest.kt
// Deviation: parsed with kotlinx-serialization instead of pcontacts'
// hand-rolled regex parser (we already depend on it). Only the two bcrypt
// sections are consumed at M1 — the openPgp section exercises
// encrypt/decrypt operations that land at M2.

package app.alpensync.core.auth

import app.alpensync.core.auth.bcrypt.ComputeKeyPassword
import app.alpensync.core.auth.bcrypt.SrpHashPassword
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Plan Rule 19 — pins the Kotlin SRP/bcrypt port against vectors captured
 * from `@protontech/crypto` 2.0.1 (generated by pcontacts'
 * `tools/vectors/capture.js`, matching go-srp). The JSON lives at
 * `core/auth/src/test/resources/proton-crypto-vectors.json`, copied
 * byte-identical from pcontacts.
 */
class CapturedVectorsTest {

    @Serializable
    private data class KeyPasswordVector(
        val label: String,
        val password: String,
        val saltB64: String,
        val expected: String,
    )

    @Serializable
    private data class SrpVector(
        val label: String,
        val password: String,
        val saltB64: String,
        val modulusHex: String,
        val version: Int,
        val expectedHex: String,
    )

    @Serializable
    private data class Vectors(
        @SerialName("computeKeyPassword") val keyPassword: List<KeyPasswordVector> = emptyList(),
        @SerialName("srpHashPassword") val srpHashPassword: List<SrpVector> = emptyList(),
    )

    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun computeKeyPassword_matches_captured_vectors() {
        val vectors = loadVectors()
        assertTrue("vectors file must contain computeKeyPassword entries", vectors.keyPassword.isNotEmpty())
        for (v in vectors.keyPassword) {
            val actual = ComputeKeyPassword.derive(v.password.toCharArray(), v.saltB64)
            assertEquals("computeKeyPassword vector '${v.label}' mismatch", v.expected, actual)
        }
    }

    @Test
    fun srpHashPassword_matches_captured_vectors() {
        val vectors = loadVectors()
        assertTrue("vectors file must contain srpHashPassword entries", vectors.srpHashPassword.isNotEmpty())
        for (v in vectors.srpHashPassword) {
            val modulusBytes = hexToBytes(v.modulusHex)
            val actual = SrpHashPassword.derive(v.password.toCharArray(), v.saltB64, modulusBytes)
            assertEquals("srpHashPassword vector '${v.label}' mismatch", v.expectedHex, actual.toHex())
        }
    }

    private fun loadVectors(): Vectors {
        val stream = requireNotNull(javaClass.getResourceAsStream("/proton-crypto-vectors.json")) {
            "proton-crypto-vectors.json must be on the test classpath"
        }
        return json.decodeFromString(Vectors.serializer(), stream.use { it.readBytes().toString(Charsets.UTF_8) })
    }

    private fun hexToBytes(hex: String): ByteArray {
        require(hex.length % 2 == 0) { "hex string must have even length" }
        return ByteArray(hex.length / 2) {
            ((Character.digit(hex[it * 2], 16) shl 4) + Character.digit(hex[it * 2 + 1], 16)).toByte()
        }
    }

    private fun ByteArray.toHex(): String = joinToString("") { "%02x".format(it) }
}
