// SPDX-License-Identifier: GPL-3.0-only
// SPDX-FileCopyrightText: 2026 WFT345 and AlpenSync contributors
// Adapted from pcontacts (GPL-3.0), https://github.com/andreabenetton/pcontacts @ bf9b0c5,
// path core/storage/src/main/kotlin/io/pcontacts/core/storage/KeystoreAesGcmKek.kt
// Deviation: the KEK alias is caller-supplied (per-account aliases,
// `alpensync.kek.<accountId>`), not a single global alias.

package app.alpensync.core.auth.store

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Second crypto layer for the mailbox keyPassword (ADR 0004 Section 3): a
 * Keystore-backed AES-256-GCM key under a per-account alias. Wrapping the
 * keyPassword under a Keystore key (rather than relying on
 * EncryptedSharedPreferences alone) gives hardware-backed key isolation on
 * StrongBox/TEE devices and a clean deletion point on logout.
 *
 * Wire format for [wrap] output:
 *   [0..11]  random 96-bit IV
 *   [12..]   GCM ciphertext + 128-bit tag
 */
class KeystoreAesGcmKek(
    private val alias: String,
) {

    fun wrap(plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateKey())
        val iv = cipher.iv // 12 bytes for GCM, generated by the provider
        require(iv.size == IV_BYTES) { "expected 12-byte GCM IV, got ${iv.size}" }
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext
    }

    fun unwrap(wrapped: ByteArray): ByteArray {
        require(wrapped.size > IV_BYTES) { "wrapped payload too short" }
        val iv = wrapped.copyOfRange(0, IV_BYTES)
        val ciphertext = wrapped.copyOfRange(IV_BYTES, wrapped.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateKey(), GCMParameterSpec(GCM_TAG_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    /** Deletes the alias entirely. The next [wrap] provisions a fresh key. */
    fun delete() {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        if (ks.containsAlias(alias)) ks.deleteEntry(alias)
    }

    private fun getOrCreateKey(): SecretKey {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        val existing = ks.getKey(alias, null) as? SecretKey
        if (existing != null) return existing

        val gen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        gen.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT,
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(KEY_SIZE_BITS)
                // User-presence binding (biometric) is intentionally NOT
                // enabled so background sync can decrypt without a
                // foreground UI.
                .build(),
        )
        return gen.generateKey()
    }

    private companion object {
        const val KEYSTORE_PROVIDER: String = "AndroidKeyStore"
        const val IV_BYTES: Int = 12
        const val GCM_TAG_BITS: Int = 128
        const val KEY_SIZE_BITS: Int = 256
    }
}
